spring:
    datasource:
#        url: jdbc:mysql://localhost:3306/board?useSSL=false&serverTimezone=Asia/Seoul
#        username: root
#        password: 1234
        url: jdbc:mysql://awseb-e-yppd3bxyfs-stack-awsebrdsdatabase-zrxlbculosmb.cp44w26cwae3.ap-northeast-2.rds.amazonaws.com/board?useSSL=false&serverTimezone=Asia/Seoul
        username: fastcam
        password: 114802gud
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    properties:
        hibernate:
            format_sql: true
